"""Move existing rows onto the current AdFormat values.

The placement names changed, so rows written under the old ones would no
longer validate. Run against each database after deploying.

Usage:
    python migrate_ad_formats.py [--dry-run]
"""

import argparse

from sqlalchemy import text

from database import engine

# Old value -> current value. Placements with no equivalent collapse onto the
# standard banner rather than being dropped, so no template or campaign is
# left holding a format the API will reject.
REMAP = {
    "ISLAND": "HOOD_PICKS_BANNER",
    "TWO_X": "DOUBLE_WIDTH_BANNER",
    "NOTICE_BOARD": "HOOD_PICKS_BANNER",
    "LIFT_BRANDING": "HOOD_PICKS_BANNER",
    "GATE_ARCH": "HOOD_PICKS_BANNER",
    "STANDEE": "HOOD_PICKS_BANNER",
}
CURRENT = {"HOOD_PICKS_BANNER", "DOUBLE_WIDTH_BANNER"}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    with engine.connect() as c:
        print("=== before ===")
        for tbl, col in (("society_ad_pricing", "ad_format"),
                         ("ad_templates", "format"),
                         ("campaigns", "ad_format")):
            for v, n in c.execute(text(f"select {col}, count(*) from {tbl} group by 1 order by 1")):
                print(f"  {tbl}.{col:12} {v:20} {n}")

    if args.dry_run:
        print("\ndry run - nothing written")
        return

    with engine.begin() as c:
        # Pricing is regenerated by seed_pricing.py, so retired formats are
        # deleted rather than remapped - keeping them would collide with the
        # unique (society, format) constraint.
        removed = c.execute(text(
            "delete from society_ad_pricing where ad_format not in ('HOOD_PICKS_BANNER','DOUBLE_WIDTH_BANNER')"
        )).rowcount
        print(f"\nremoved {removed} pricing rows on retired formats")

        for tbl, col in (("ad_templates", "format"), ("campaigns", "ad_format")):
            for old, new in REMAP.items():
                n = c.execute(
                    text(f"update {tbl} set {col} = :new where {col} = :old"),
                    {"new": new, "old": old},
                ).rowcount
                if n:
                    print(f"  {tbl}.{col}: {old} -> {new}  ({n} rows)")

    with engine.connect() as c:
        print("\n=== after ===")
        for tbl, col in (("society_ad_pricing", "ad_format"),
                         ("ad_templates", "format"),
                         ("campaigns", "ad_format")):
            rows = c.execute(text(f"select {col}, count(*) from {tbl} group by 1 order by 1")).all()
            for v, n in rows:
                flag = "" if v in CURRENT else "   <-- STILL INVALID"
                print(f"  {tbl}.{col:12} {v:20} {n}{flag}")
            if not rows:
                print(f"  {tbl}.{col:12} (empty)")


if __name__ == "__main__":
    main()
